propel:
  sf_guard_group:
    _attributes: { phpName: sfGuardGroup }
    id: { phpName: Id, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', primaryKey: true, autoIncrement: true, required: true }
    name: { phpName: Name, type: VARCHAR, size: '255', required: true }
    description: { phpName: Description, type: LONGVARCHAR, required: false }
  sf_guard_group_permission:
    _attributes: { phpName: sfGuardGroupPermission, isCrossRef: true }
    group_id: { phpName: GroupId, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', primaryKey: true, required: true, foreignTable: sf_guard_group, foreignReference: id, onDelete: CASCADE }
    permission_id: { phpName: PermissionId, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', primaryKey: true, required: true, foreignTable: sf_guard_permission, foreignReference: id, onDelete: CASCADE }
    _indexes: { sf_guard_group_permission_FI_2: [permission_id] }
  sf_guard_permission:
    _attributes: { phpName: sfGuardPermission }
    id: { phpName: Id, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', primaryKey: true, autoIncrement: true, required: true }
    name: { phpName: Name, type: VARCHAR, size: '255', required: true }
    description: { phpName: Description, type: LONGVARCHAR, required: false }
  sf_guard_remember_key:
    _attributes: { phpName: sfGuardRememberKey }
    user_id: { phpName: UserId, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', primaryKey: true, required: true, foreignTable: sf_guard_user, foreignReference: id, onDelete: CASCADE }
    remember_key: { phpName: RememberKey, type: VARCHAR, size: '32', required: false }
    ip_address: { phpName: IpAddress, type: VARCHAR, size: '50', primaryKey: true, required: true }
    created_at: { phpName: CreatedAt, type: TIMESTAMP, required: false }
  sf_guard_user:
    _attributes: { phpName: sfGuardUser }
    id: { phpName: Id, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', primaryKey: true, autoIncrement: true, required: true }
    username: { phpName: Username, type: VARCHAR, size: '128', required: true }
    algorithm: { phpName: Algorithm, type: VARCHAR, size: '128', required: true, defaultValue: sha1 }
    salt: { phpName: Salt, type: VARCHAR, size: '128', required: true }
    password: { phpName: Password, type: VARCHAR, size: '128', required: true }
    created_at: { phpName: CreatedAt, type: TIMESTAMP, required: false }
    last_login: { phpName: LastLogin, type: TIMESTAMP, required: false }
    is_active: { phpName: IsActive, type: BOOLEAN, size: '1', required: true, defaultValue: true }
    is_super_admin: { phpName: IsSuperAdmin, type: BOOLEAN, size: '1', required: true, defaultValue: false }
    _uniques: { sf_guard_user_U_1: [username] }
  sf_guard_user_group:
    _attributes: { phpName: sfGuardUserGroup, isCrossRef: true }
    user_id: { phpName: UserId, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', primaryKey: true, required: true, foreignTable: sf_guard_user, foreignReference: id, onDelete: CASCADE }
    group_id: { phpName: GroupId, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', primaryKey: true, required: true, foreignTable: sf_guard_group, foreignReference: id, onDelete: CASCADE }
    _indexes: { sf_guard_user_group_FI_2: [group_id] }
  sf_guard_user_permission:
    _attributes: { phpName: sfGuardUserPermission, isCrossRef: true }
    user_id: { phpName: UserId, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', primaryKey: true, required: true, foreignTable: sf_guard_user, foreignReference: id, onDelete: CASCADE }
    permission_id: { phpName: PermissionId, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', primaryKey: true, required: true, foreignTable: sf_guard_permission, foreignReference: id, onDelete: CASCADE }
    _indexes: { sf_guard_user_permission_FI_2: [permission_id] }
